### ISSUE TITLE
Configurable path to sass-lint.yml

### ISSUE THREAD

**Issue by davetgreen** [sasstools/grunt-sass-lint#1]
It would be useful if an option could be passed to sass-lint that would let you change the path to the config file if you'd prefer not have another file in the project root, or have a dedicated folder containing all of your config files.

Edit: I've posted this in the main sass-lint repo as it's more relevant there, but I thought I'd leave this issue open here for the ability to pass the option through.

**Comment by micahgodbolt** [comment]
Yeah, in my initial implementation I was trying to sort out how that worked. Not sure if the option was available when that work was done. If you find that the path to yml file can be passed in, PRs are always accepted!

**Comment by davetgreen** [comment]
@micahgodbolt I'll take a look this weekend cheers!

**Comment by davetgreen** [comment]
#4 deals with this so I'll close this issue @micahgodbolt

**Comment by micahgodbolt** [comment]
Cool! I'll check out #4.
