### ISSUE TITLE
Does not run on multiple files

### ISSUE THREAD

**Issue by gavinr** [sasstools/grunt-sass-lint#10]
* node: v0.10.36
* npm: v1.4.28
* grunt-sass-lint 0.1.0-beta.4

If I run the linter with one file in my `target` array, I get 11 warnings:
![one-file-config](https://cloud.githubusercontent.com/assets/209355/10950510/9ba8eb72-82fd-11e5-8a34-c2a4fe448998.PNG)
![one-file](https://cloud.githubusercontent.com/assets/209355/10950513/9d8169ba-82fd-11e5-87d7-16303705fefb.PNG)

Great. Everything above looks like it's running correctly. Now I add an additional file to the `target` array (as the first item in the array):
![two-files-config](https://cloud.githubusercontent.com/assets/209355/10950532/b7183796-82fd-11e5-9060-7ca4585cc4e0.PNG)
... and now I'm only getting linting errors for the first file (3 warnings only):
![two-files](https://cloud.githubusercontent.com/assets/209355/10950546/c751bcfe-82fd-11e5-913c-d0095bdbab01.PNG)

... so it appears that the second file is not being linted, even though it says it is.

**Comment by DanPurdy** [comment]
Just had a look at this, it does indeed look that way and looks set to use only one target, presumably a glob... https://github.com/sasstools/grunt-sass-lint/blob/master/tasks/sass-lint.js#L13

I dont use the grunt plugin but might have a look at this soon if it doesn't get picked up

**Comment by gavinr** [comment]
Thanks @DanPurdy - would appreciate if you could take a look.

**Comment by DanPurdy** [comment]
Hi @gavinr sorry it's taken so long but i've been looking at some sass-lint issues today and got to looking at this. `sass-lint` only accepts a single include pattern so either a single file or a glob. You can then exclude an array of files specifically. If you want to run against an array of targets you'd need to repeat your grunt task for each file as it stands.

**Comment by gavinr** [comment]
Thanks for investigating @DanPurdy!
