### ISSUE TITLE
Log not visible in dark terminals

### ISSUE THREAD

**Issue by xDae** [sasstools/grunt-sass-lint#20]
Some parts in the report log are note visible in dark themes terminal

at the bottom, the selected log can be legible

<img width="832" alt="captura de pantalla 2016-04-20 a las 11 42 42" src="https://cloud.githubusercontent.com/assets/6037190/14670379/359221a4-06ed-11e6-89ce-a487db7cd935.png">

**Comment by DanPurdy** [comment]
Is this just not a problem with your terminal theme? Grunt sass lint doesn't add any formatting to the output.

**Comment by xDae** [comment]
true, its a problem with my terminal theme
