### ISSUE TITLE
Problem with trailing semicolon

### ISSUE THREAD

**Issue by OBellon** [sasstools/grunt-sass-lint#28]
Hi all,

I'm having problems with the trailing semicolon rule, because it is just linting ok when it is the last line of a block. For example:

```sass
body {
    display: block;
    background: red
}
```
 Would break.

But:

```sass
body {
    display: block
    background: red;
}
```

Would not.

Do you have any fixes on this?

I don't know if this should be here, or in sass-lint repo, so sorry if it is the wrong place.

Thanks in advance.

**Comment by DanPurdy** [comment]
Hey @OBellon could you add it to the sass-lint repo please. The grunt plugin just consumes sass-lint.

Thanks!
