### ISSUE TITLE
Warning: previous.is is not a function

### ISSUE THREAD

**Issue by ajsb85** [sasstools/grunt-sass-lint#30]
```
Running "sasslint:target" (sasslint) task
Warning: previous.is is not a function Use --force to continue.

Aborted due to warnings.


Execution Time (2016-10-04 17:03:40 UTC+2)
loading tasks     1.3s  ███████████████████████████████████████ 86%
sasslint:target  220ms  ███████ 14%
Total 1.5s


```

**Comment by DanPurdy** [comment]
this is an issue with Sass-lint itself. I think you've already opened an issue there, if you have / haven't could you please provide as much information as possible so we can get to the bottom of the problem as fast as possible! Thanks

**Comment by ajsb85** [comment]
@DanPurdy It's here:
https://github.com/sasstools/sass-lint/issues/887
I can send you `sass` files to test.
Thanks.

**Comment by DanPurdy** [comment]
@ajsb85 If you could add it to that issue that would be great, thanks! I'll look into your PR too and see what needs to change for the tests to pass.

👍
