### ISSUE TITLE
npm install errors unless version is specified.

### ISSUE THREAD

**Issue by FStop** [sasstools/grunt-sass-lint#6]
running `npm install grunt-sass-lint --save-dev` I get the following error:

```
npm ERR! notarget No compatible version found: grunt-sass-lint@'*'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0-beta.1","0.1.0-beta.2","0.1.0-beta.3"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

`npm install grunt-sass-lint@0.1.0-beta.3 --save-dev` works

**Comment by DanPurdy** [comment]
Just tried this but i'm afraid I can't recreate it, there must be something else up here or npm was having a little moment..

![screen shot 2015-10-12 at 22 38 26](https://cloud.githubusercontent.com/assets/1386054/10439472/ff1797b8-7131-11e5-9d89-6545088a9993.png)

**Comment by DanPurdy** [comment]
Have you got the details of your npm version, node version etc..

**Comment by FStop** [comment]
Well it looks like my node was way out of date, version 2.11.2. I updated and now have 

npm 3.3.6
node 0.12.5

I ran `npm install grunt-sass-lint --save-dev ` after updating and it did a bunhc of stuff before erroring:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "grunt-sass-lint" "--save-dev"
npm ERR! node v0.12.5
npm ERR! npm  v3.3.6
npm ERR! path .../node_modules/js-yaml/node_modules/esprima/bin/esparse.js
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, chmod '.../node_modules/js-yaml/node_modules/esprima/bin/esparse.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```
I ran it a second time and it seemed to succeed.

**Comment by DanPurdy** [comment]
Going to put this down as just a npm issue then.
