### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by DanPurdy** [sasstools/grunt-sass-lint#7]
Just noticed that when installing grunt-sass-lint from npm it brings down sass-lint 1.0.0 

see here https://github.com/sasstools/sass-lint/issues/295

Looks like even though package.json has been updated this package hasn't been pushed to NPM..

Should probably do that quite soon as this is seriously behind now!

**Comment by micahgodbolt** [comment]
Thankd @DanPurdy . I'll take a quick look. They're moving fast over there!

**Comment by micahgodbolt** [comment]
Alright. Updated on NPM. I'll probably push out a 0.1.0 proper once I get a chance to test out all the new functionality

**Comment by DanPurdy** [comment]
Awesome, thanks @micahgodbolt 

Yep, we've been hammering away at development on sass-lint it's really starting to shape up now!

If you need any help with any specific testing give me a shout and i can lend a hand.
