### ISSUE TITLE
Option for warning to fail the build

### ISSUE THREAD

**Issue by lawlesscreation** [sasstools/grunt-sass-lint#8]
Is there a way to enforce warning to fail the build? At present it returns:

```
  91:5  warning  Indentation of 4, expected 2  indentation
  92:5  warning  Indentation of 4, expected 2  indentation
  93:5  warning  Indentation of 4, expected 2  indentation

✖ 44 problems (0 errors, 44 warnings)

Done, without errors.
```

But it would be nice if warning could be set to fail either as a global or per-rule.

**Comment by DanPurdy** [comment]
Can't you use errors? Set the rules to severity 2

**Comment by lawlesscreation** [comment]
@DanPurdy ah yes, sorry. I can configure it through the `.sass-lint.yml` file. Thanks!

**Comment by DanPurdy** [comment]
That's ok, no worries!

**Comment by lawlesscreation** [comment]
@DanPurdy actually... should this happen after setting the severity to 2:

```
  92:5  error  Indentation of 4, expected 3                                indentation
  93:5  error  Indentation of 4, expected 3                                indentation

✖ 45 problems (45 errors, 0 warnings)

Done, without errors.
```

It now reports as an error but returns `Done, without errors.`?

**Comment by fernandoPalaciosGit** [comment]
Hello @DanPurdy I use intensively this plugin to ensure deploying releases without a lot os sass errors, but does not stop execution on Errors, any idea to force stop the execution next grunt task?

![log sasslint](http://cruzalosdedos.es/media/sasslint-error-unblocked.png)
