### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by lawlesscreation** [sasstools/grunt-sass-lint#9]
I'm not sure if it's my setup but using using * selectors in the target results in the error:

```
Warning: Cannot read property 'start' of undefined Use --force to continue.
```

So this works:

```
    options: {
        configFile: '.sass-lint.yml'
    },
    target: ['scss/style.scss']
```

But this doesnt:

```
    options: {
        configFile: '.sass-lint.yml'
    },
    target: ['scss/*.scss']
```

Anyone else experience this problem? Using node 4.1.1 if that makes any difference.

**Comment by kevinlbatchelor** [comment]
same for me :(

**Comment by kevinlbatchelor** [comment]
https://github.com/sasstools/sass-lint/issues/62

**Comment by gavinr** [comment]
I'm getting this issue too:
```
Running "sasslint:target" (sasslint) task
Warning: Cannot read property 'start' of undefined Use --force to continue.
```

* node: v0.10.36
* npm: v1.4.28
* grunt-sass-lint 0.1.0-beta.4

@kevinlbatchelor I've read through https://github.com/sasstools/sass-lint/issues/62, but I'm not clear on the resolution - is the issue a tabs v spaces thing, or something else?

**Comment by DanPurdy** [comment]
It's probably to do with the indentation rule, if you're using tabs then this will definitely fail at the moment, theres an explanation [here]()

If you're using spaces then it could be down to the line ending characters being used, CLRF is causing an issue as notes [here]()

We're a bit loathed to update the indentation rule too much at the moment due to the current state of tabs in the AST and the fact that when we update to the latest version of `gonzales-pe` we'll need to rewrite the rule anyway.

**Comment by lawlesscreation** [comment]
Has anyone been able to create a solution for this? Not being able to pass `*.scss` to the target makes checking multiple files tedious. The files I'm testing are using 4 spaces for tabs and should be using `lf` line endings.

Any help appreciated.

**Comment by Kjuib** [comment]
I had this same issue. I resolved it by changing the line ends of ALL files to LF. There were 2 of the 20+ files that were on CRLF. Unfortunately when it errors it doesn't list which file it errored on. I had to edit the sass-lint files to added a few console logs.

**Comment by DanPurdy** [comment]
The good news is we may be able to do something about this soon. We're in the process of updating to the latest version of the AST we use to parse your files, it's fixed a lot of issues now. Once that is complete we'll be able to fix any issues with tabs and line endings. Sorry for the delay..

**Comment by kevinlbatchelor** [comment]
@Kjuib where did you stick your console.log?

**Comment by kevinlbatchelor** [comment]
@Kjuib figured it out, couldn't remember what you did. FYI a console.log in line 179 of index.js in the sass-lint directory will show you what file is the process is dyeing on. Then go change the line endings on that file.

**Comment by lawlesscreation** [comment]
@kevinlbatchelor for completness I thought I would add the console.log code you're referring to on line 179:

```
  files.forEach(function (file) {
    console.log('file #=> ' + file);
    ...
  });
```

**Comment by lawlesscreation** [comment]
@DanPurdy fingers crossed the latest version of AST helps, I don't seem to be able to exclude files either :( e.g.:

```
grunt.initConfig({
    sasslint: {
        options: {
            configFile: 'config/.sass-lint.yml',
        },
        target: [
            'location/*.scss',
            '!location/vendor.scss'
        ]
    }
});
```

**Comment by DanPurdy** [comment]
This is another problem that we hope to have fixed soon. The sass-lint method that both grunt-sass-lint and gulp-sass-lint use is post the point where we check for file includes / excludes which is a bit of a frustration. I'll be looking at getting it sorted in sass-lint itself soon so we don't have to worry about parsing configs in these plugins.

**Comment by lawlesscreation** [comment]
Super!

**Comment by obrejla** [comment]
Adding `/**/*.scss` to path also generates this error. I need to scan entire project, so writing all paths manually is not possible. Thanks.

**Comment by quicoto** [comment]
Same here, being able to at least `/*.scss` is a must. Not necessary to scan all folders but at least all files within the path. Having .scss invites to separate code into components, etc...

Any workaround or solution in the horizon?

Thank you.

**Comment by DanPurdy** [comment]
Can you try running this just using the sass-lint Cli without grunt please.. Parse errors should no longer dump you out and instead return a parse error as a lint error.. 

If it's still throwing you out then I need to know a bit more about your settings.. The issue is not with the globbing of your files so you can definitely use those path specifications. If there's something in one of those files crashing it though we need to see what.. 

The original issue is a problem with the AST we're using, it doesn't handle crlf line endings or tabs and generally just has a few issues on Windows. A lot of these are sorted in sass-lint 1.6 when we release that as it includes an update to the latest version of the AST.. The only thing blocking us releasing that is the AST includes a bash specific post install script which renders it completely useless on most people's windows machines.. Our hands are tied until someone updates the AST which is out of our hands..

**Comment by lawlesscreation** [comment]
Hey @DanPurdy,

Finally got around to testing this,

> Can you try running this just using the sass-lint Cli without grunt please.. Parse errors should no longer dump you out and instead return a parse error as a lint error..

So using Node v4.4 with nvm and with sass-lint v1.5.1 on OSX:

```
$ sass-lint '*.scss' -v -q
.nvm/versions/node/v4.4.0/lib/node_modules/sass-lint/lib/rules/indentation.js:57
                  'line': node.content[i + 1].start.line,
                                             ^

TypeError: Cannot read property 'start' of undefined
    at processNode (.nvm/versions/node/v4.4.0/lib/node_modules/sass-lint/lib/rules/indentation.js:57:46)
    at processNode (.nvm/versions/node/v4.4.0/lib/node_modules/sass-lint/lib/rules/indentation.js:96:9)
    at processNode (.nvm/versions/node/v4.4.0/lib/node_modules/sass-lint/lib/rules/indentation.js:96:9)
    at processNode (.nvm/versions/node/v4.4.0/lib/node_modules/sass-lint/lib/rules/indentation.js:96:9)
    at processNode (.nvm/versions/node/v4.4.0/lib/node_modules/sass-lint/lib/rules/indentation.js:96:9)
    at Object.module.exports.detect (.nvm/versions/node/v4.4.0/lib/node_modules/sass-lint/lib/rules/indentation.js:100:5)
    at .nvm/versions/node/v4.4.0/lib/node_modules/sass-lint/index.js:123:27
    at Array.forEach (native)
    at Function.sassLint.lintText (.nvm/versions/node/v4.4.0/lib/node_modules/sass-lint/index.js:122:11)
    at .nvm/versions/node/v4.4.0/lib/node_modules/sass-lint/index.js:179:21
```

> The original issue is a problem with the AST we're using, it doesn't handle crlf line endings or tabs and generally just has a few issues on Windows. A lot of these are sorted in sass-lint 1.6 when we release that as it includes an update to the latest version of the AST.

Did you want me to raise this as a different issue to track the two if they are not related?
